name: Say Hi

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: echo "Hiiii Lenar !!"
      - name: Tell me the Date
        run: date
      - run: ls -l